### ISSUE TITLE
`Array#hash` producing too many collisions

### ISSUE THREAD

**Issue by richardboehme** [seven1m/natalie#188]
I'm currently tinkering around with `Hash#hash` and noticed this bug in `Array#hash`:
```ruby
[2, 2].hash == [1, 1].hash
# => true
```

`[2, 2].hash` will return 100019 which is the starting point of the hash calculation, because `(2.hash * 207269) ^ (2.hash * 207269)` will eliminate each other. My first thought of fixing this is multiplying with a random prime number instead of a fixed one. Would this work?

**Comment by seven1m** [comment]
Whoops! @TheGrizzlyDev and I worked on that, but that mistake is mine. The recursive array specs are mind bending, but I feel confident adding a random number won't fix it. 😕

I will try to take another look at this soon.

**Comment by TheGrizzlyDev** [comment]
> I feel confident adding a random number won't fix it. confused
I feel like we've been here already ahhahaha. A similar but less naive approach would be to just shift at each iteration :)

**Comment by seven1m** [comment]
@TheGrizzlyDev you're a genius. (That worked.)

**Comment by TheGrizzlyDev** [comment]
> @TheGrizzlyDev you're a genius. (That worked.)

Ahahahaha thanks! I've spent enough time on it to think in hashes

**Comment by richardboehme** [comment]
Thanks for fixing this so fast! 😄 Sadly, I think this is not enough yet. Firstly it does not work with nested arrays:

```ruby
[[1, 2], [3, 2]].hash == [[1, 3], [2, 3]]
# => true
```
The two 2s and the 3s are eliminating each other.

Secondly, as nat_int_t is "only" 64 bit, it will not work if we shift more than 64 times (when the array is bigger than 64):

```ruby
def generate_array(i)
  [].tap do |out|
    66.times { out << i }
  end
end

generate_array(2).hash == generate_array(3).hash
# => true
```

**Comment by seven1m** [comment]
Bummer. Well I'll have to take another stab at it later. If you have ideas, by all means, go for it. 😉

**Comment by TheGrizzlyDev** [comment]
this keeps getting better and better ahahhahah. How about we take a page from DES/AES which have the same issue with using multiple rounds and having just a single key (in this case our prime number)?
We could:
- select a big enough prime number (or any number big enough that if taken in smaller bits would still have a somewhat reasonable distribution of 0s and 1s and at least with more bits than nat_int_t)
- for each item we get the hash of, we xor it with a prime number AND then xor it with a subkey of the aforementioned number of 64 bits in length
- we do a circular shift (not sure that's the name of it, but basically a shift where a digit 'leaving' on one side would just 'come back' from the other) and then repeat the process for the next item?

PS: I hope you find more issues if this fixes the above, absolutely loving it :D

**Comment by TheGrizzlyDev** [comment]
PPS: the above as an issue with periodicity, as in after a full-rotation of the key value would start cancelling each other out again. A simple solution to that would just be having another key, used the same way and with the same property but with a different length so that collision only happen after N (length of first key) * M (length of the second key) iterations. Long enough keys would cover any practical purpose. Again, let me know if this also misses some scenarios as it is so fun :)

**Comment by richardboehme** [comment]
Naive question: What speaks against adding the hashes instead of xoring them? We would not have the problem with eliminating entries than. However, I see overflow being a problem maybe?

**Comment by seven1m** [comment]
Try it and see! 😉 (I honestly don't remember why I chose xor -- probably Stack Overflow told me to lol 😆)

**Comment by TheGrizzlyDev** [comment]
When overflowing you'd end up just having 1s in the rightmost part of the hash, therefore making collisions more likely. It'd work and be simple but would not be as effective I guess as the range of collisions would just be on the lower end of the bit array... I wouldn't mind that to be honest depending on how and where hash is used. @seven1m you probably know that better, but I reckon it wouldn't be too bad just for hashes :)

**Comment by TheGrizzlyDev** [comment]
How about subtractions though? Ordering is implicitly considered as in non-commutative as addition is, it doesn't cancel out the previous value but rather "adds" to it unlike xor and wouldn't overflow in the same way as additions which would lead to a less effective distribution of 0s and 1s

**Comment by seven1m** [comment]
OK, I took another stab at it. The main problem was that I was calling `Array::eql` and treating it like a bool (forgot to call `is_truthy()`), so that was half the battle. I also decided to xor the array index and added MOAR PRIMES lol. :joy: 

Anyway, let me know if y'all find any more weird cases on this one @richardboehme @TheGrizzlyDev. <3

**Comment by TheGrizzlyDev** [comment]
this implementation should fail with repeating values and since xor is commutative and indexes are values so 'close' to each other they will end up cancelling each other out far too often. The second one is really easy to demonstrate:
00 XOR
01 XOR
10 XOR
11 =
00 => so with a given periodicity, xor-ring the index will cancel the final result of the whole operation out, so it pretty much provides no value in terms of avoiding collisions (hence why I suggested circular shifting before - not sure circular shifting is an actual name or I just came up with a term to explain what I am imagining, in which case please let me know hahahaha)

The first issue though is a bit harder, so I will make an example script to prove it :)

**Comment by TheGrizzlyDev** [comment]
Created a script to demonstrate this since I am too lazy to prove it otherwise :D 

```ruby
found_hashes = []
hashes = (0..100).map do |length| 
    current_hash = (0..length).to_a.map { |x| 0 }.hash 
    found_index = found_hashes.find_index current_hash
    if found_index
        p "Found a repetition with length = #{length} and the previous length = #{found_index} => #{current_hash}"
    else
        found_hashes << current_hash
    end 
end
```

with 101 tests there were only 61 unique values and the greater this number goes the higher collisions should get, in theory getting closer and closer to 50% of collisions

**Comment by seven1m** [comment]
I'm leaving this open for a few days until @TheGrizzlyDev decides to stop poking at it and moves on. :laughing: :laughing:

**Comment by TheGrizzlyDev** [comment]
about that, done some preliminary testing and found out that:
- this implementation of hash collides far less than the MRI one :D 
- we can improve a lot just by shifting the amount of digits we shift (my theory was right on how that affects the output, but the guess was really bad ahahahaha) and this should be easy enough :^)
- the implementation I just pushed of Array::repeated_combination is unbearably slow, especially when compared with MRI's one, so we should try to improve that as well to get a better test bench (getting repeated_transpositions would probably help as well)

I'll go a bit deeper tomorrow and maybe try to improve it all, but there's quite a few quick wins here and this has been quite fun :^)

**Comment by seven1m** [comment]
There's so much in way of performance optimization we can do, first and foremost will be a method cache. But we'll have plenty of time for that... 😉
